{% set name = "radical.entk" %}
{% set version = "1.42.0" %}
{% set sha256 = "7bc9566897ea7fb46b65971c194f01724aa710edc1817d6fcd973cea7f6a061b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  skip: true  # [py2k or win]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - radical.utils >=1.40
    - radical.pilot >=1.40

test:
  imports:
    - radical.entk

about:
  home: https://github.com/radical-cybertools/radical.entk
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: RADICAL-EnTK is an ensemble execution system written in Python
  description: |
    RADICAL-EnTK (Ensemble Toolkit) is a Python framework for developing and 
    executing applications comprised of multiple sets of tasks, aka ensembles. 
    Ensemble Toolkit has the following unique features, (i) abstractions that 
    enable the expression of various task graphs, (ii) abstraction of resource 
    management and task execution, (iii) Fault tolerance as a first order 
    concern and (iv) well-established runtime capabilities to enable efficient 
    and dynamic usage of grid resources and supercomputers.
  dev_url: https://github.com/radical-cybertools/radical.entk
  doc_url: https://radicalentk.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - andre-merzky
    - mtitov
