{% set name = "radical.entk" %}
{% set version = "0.72.0" %}
{% set sha256 = "a33f35a64a4f8572b68d2268e820e31d761c2e4595b489f8c03ad4906a0fcabd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: True  # [py3k or win]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - radical.pilot
    - radical.utils
    - pika 0.13.0
    - pytest
    - hypothesis
    - sphinx
    
test:
  imports:
    - radical.entk
  
about:
  home: https://github.com/radical-cybertools/radical.entk
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Ensemble Toolkit (EnTK) is an ensemble execution system written in Python'
  description: |
    Ensemble Toolkit is a Python framework for developing and executing applications comprised of 
    multiple sets of tasks, aka ensembles. Ensemble Toolkit has the following unique features, (i) 
    abstractions that enable the expression of various task graphs, (ii) abstraction of resource 
    management and task execution, (iii) Fault tolerance as a first order concern and (iv) 
    well-established runtime capabilities to enable efficient and dynamic usage of grid resources 
    and supercomputers.
  dev_url: https://github.com/radical-cybertools/radical.entk
  doc_url: https://radicalentk.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - vivek-bala
    - andre-merzky
    - iparask
