# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_python2.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "R18lFZC9lAPCHXlLJR1Pc4MdxApGEac4fdY+Y2SMN2GIXroaS02DXrNfSvv4rvlM+pSfeK9NJIHQzfhDW9aiAPbcbpZDGk96olHgksfBmY8XWb3m6Fm40D6/talVggPnXsr3ZhJueGWEfrRZJ6Wtb2tcMbccolFLkEoB9lyV7ksSny97K7ZaE08Jq1lJcXqpWDGt8/YQQxq5I7XCL7RekPIF/WnBUkoRdFgt0fMYb/ELrKMzgDZgNjFLvKGMgoFiwHYLEae5eevGOHGJlGgC7mLZwg3arX8PMaYCv2PRK2dofdH8lUzjLTQ2Gt80ZkQi7WJpsvhmcU3uvhH/pPJwO7Fc2ZJI7mVSBxCCE1Z+XzzZFjQkiCzaswn9ypGzjRkWSzHcldon+60wTYZ/IQoJYNX8JJ3jZ3P4RaQ6d0/UA2WfcifUCzOIlI3kn/1W9qJoZ1oU4jZeq7puKNqWirGVCFgozoeSkaim/yKH8Y3Jk+RQl85aJpC4PA6fjkXfX7VAV4RGFdsJdyMqNQLs9jLI7revJ9I0ol55v7FNrH0QcusCo/5zA6bRMcswCSGTQGI/s/21HJP4WgLOaCgG3nx6cE/ZlLZu1Uy74v3VNPX3x7Agb/ZzizSRD/XdSN9q0krzjEZDxvdV5Q7pIjxgDZEyDb/PyWXxG1cVLjaO3j73YbY="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml